### PR TITLE
✨ Update to .Net 5.0 & ABP 4.0.0

### PR DESCRIPTION
**Pull request by enisn**
## Summary
This PR includes mgiration to .Net 5.0 and update of all ABP packages to v4.0.0-rc.4.
Also breaking changes are implemented.

## Solution
I think this solves automatically #15  and #16 compatibility problems.

### CODE REVIEW

**Comment by enisn** [comment]
Can you review @wakuflair  ?

**Comment by wakuflair** [comment]
Great! @enisn 

I will look at it ASAP.

**Comment by wakuflair** [comment]
I have two compile errors, would you check them?

```
  FakeCurrentPrincipalAccessor.cs(12, 41): [CS0507] 'FakeCurrentPrincipalAccessor.GetClaimsPrincipal()': cannot change access modifiers when overriding 'protected' inherited member 'ThreadCurrentPrincipalAccessor.GetClaimsPrincipal()'
AdminLTEPro.Web
  AdminLTEProBrandingProvider.cs(1, 47): [CS0234] The type or namespace name 'Components' does not exist in the namespace 'Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared' (are you missing an assembly reference?)
  AdminLTEProBrandingProvider.cs(7, 48): [CS0246] The type or namespace name 'DefaultBrandingProvider' could not be found (are you missing a using directive or an assembly reference?)
  AdminLTEProBrandingProvider.cs(9, 32): [CS0115] 'AdminLTEProBrandingProvider.AppName': no suitable method found to override
```

**Comment by enisn** [comment]
Sorry, I couldn't test on the test project before. Now I've fixed compile errors with commit dffcbc4.

**Comment by wakuflair** [comment]
I pulled your PR, however I still cannot run it successfully.(Maybe the sample application should be regenerated with ABP 4.0 CLI)

Would you try it in a clean folder(pull & run) ?

**Comment by wakuflair** [comment]
OK now, thanks!

**Comment by wakuflair** [comment]
I will push the new theme package after ABP 4.0 final is released.

**Comment by enisn** [comment]
Thank you @wakuflair

**Pull request merged**
